/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.demorobot.gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author USUARIO
 */
public class DemoRobot extends javax.swing.JFrame {

    /**
     * Creates new form DemoRobot
     */
    public DemoRobot() {
        initComponents();
        
        this.setSize(500,500);
        this.setLocationRelativeTo(null);
    }
    
     @Override
    
    public void paint (Graphics g){
        
        g.setColor(Color.WHITE);
        
        g.setColor(Color.GRAY);
        g.fillRect(150,50 , 100, 100);
        
        
        g.setColor(Color.BLACK);
        g.fillOval(170, 70, 20, 20); // 2 primeros coordenada x,y y los otros 2 ancho y alto
        
        g.setColor(Color.BLACK);
        g.fillOval(210, 70, 20, 20);
        
        g.setColor(Color.GRAY);
        g.fillRect(140, 160, 120, 150);
        
        g.drawRect(140, 160, 200, 15);
        g.drawRect(150, 160, 200, 15);
        
        g.drawRect(50, 160, 190, 15);
        g.drawRect(60, 160, 190, 15);
        
        g.setColor(Color.GRAY);
        g.fillRect(160, 310, 20, 70);
        
        
        g.setColor(Color.GRAY);
        g.fillRect(220, 310, 20, 70);
        
        g.setColor(Color.RED);
        g.fillRect(220, 380, 30, 20);
        
        
        g.setColor(Color.RED);
        g.fillRect(160, 380, 30, 20);
        
       
        
        
        
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       DemoRobot robot = new DemoRobot();
        robot.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
